### ISSUE TITLE
v1.0.5-beta checklist

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#1030]
- [x] Check `v1.0.5-alpha-patch2` works well.
- [x] Update release version.
- [x] Update deployed contract addresses and chainId to prod ones
- [x] Increase Max Log File Size 
- [x] Do a new tag release and also check docker release is created successfully.
- [x] Check whether the docs are updated for the release and PR to docs has been raised for beta version.
