### ISSUE TITLE
v1.3.0-alpha Checklist

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#961]
- [x]  Create a new `v1.3.0` branch from `main` branch (Only if `main` branch is updated to latest public release)
- [x] Merge current `v1` branch to newly created `v1.3.0` branch.
- [x]  Create a PR to `v1.3.0` branch for release version change
- [x]  Create a PR to `v1.3.0` branch to change contract addresses to staging addresses
- [x] Create a new release with tag `v1.3.0-alpha`
- [x]  Create a docker release for latest release
