### ISSUE TITLE
Release checklist for v1.0.5

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/oracle-node#971]
- [x] Release alpha on testnet

- [x] Release beta on mainnet

- [ ] Release production on mainnet

Tasks :
- [x] Update razor-go version  
- [x] Merge update version PR to `v1.0.5`. 
- [x] Create a new release

After releasing `v1.0.5`: 
 - [x] Check new docker tag created with latest release once released
 - [x] Make docker image changes in docs (https://github.com/razor-network/docs-v2/issues/64)
- [x] Check docs are updated correctly (https://github.com/razor-network/docs-v2/issues/64), Merge docs PR.
- [x] Merge `v1.0.5` to main once released
