### ISSUE TITLE
Move constant values used to core/constants.go and use them throughout

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#986]
- [x] dispute.go keep gasLimitMultiplier as a constant and add a comment on why its being used as that (#870)
- [x] Move path.go strings to constants.go (#830)
- [x] change common.hash to nil hash throughout (#845)
