### ISSUE TITLE
Code CleanUp (Changes from v1-audit)

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#988]
- [x] 1.  Refactors (#864)

-  change getDelayedState to getBufferedState
-  remove uint64 from block time
-  change int to uint in constants
-  getSalt cleanup (typos)
-  Change handleRevealState to checkForLastCommitted
-  CalculateBlockNumberAtEpochBeginning rename to EstimateBlockNumberAtEpochBeginning
-  GetStatesAllowed rename to GetFormattedStateNames and remove the comma logic
-  ClaimStakeReward rename to ClaimStakerReward

- [x] 2. tx hash logging needs to be more consistent throughout (#846)
- [x] 3. remove redundant uint typecast , In GetEpoch(), uint64 needs to be removed (#844)
- [x] 4. Update coinContract to erc20contract (#842)
- [x] 5. Move standard logger json formatter to common in logger.go/initialise logger (#833)
