### ISSUE TITLE
Log Changes (from v1-audit)

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#993]
- [x]  log changes (https://github.com/razor-network/oracle-node/issues/865)
- [x]  Add comment in constants.go about do not modify (https://github.com/razor-network/oracle-node/issues/829)
- [x]  Add a warning for check eth balance that warns user that balance is low (https://github.com/razor-network/oracle-node/issues/840)
